# Generated by Django 3.2.7 on 2021-10-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_goods_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
